### ISSUE TITLE
starchat container requires mounted wait-for-it.sh

### ISSUE THREAD

**Issue by jlumme** [GetJenny/starchat-docker#1]
For me running the starchat with docker-compose requires mounting the wait-for-it.sh file for starchat container, could it be added to the container?

**Comment by angleto** [comment]
Hello @jlumme, the container does include the wait-for-it.sh script and I could not reproduce the issue. Are you using some old version  of starchat-docker? I suggest you to update to the latest version v1.0.1 or v1.0 or master.

**Comment by jlumme** [comment]
I'm getting this when I use `elegansio/starchat:3.0.0-rc8` from the docker-compose script of this repository, when building the image my self from source everything seems to work

**Comment by angleto** [comment]
Could you try this command? :
```bash
docker run elegansio/starchat:3.0.0-rc8 stat /starchat/scripts/utils/wait-for-it.sh
```

This is what it returns on my computer:
```bash
starchat-docker$ docker run elegansio/starchat:3.0.0-rc8 stat /starchat/scripts/utils/wait-for-it.sh
  File: ‘/starchat/scripts/utils/wait-for-it.sh’
  Size: 387             Blocks: 8          IO Block: 4096   regular file
Device: 31h/49d Inode: 68          Links: 1
Access: (0764/-rwxrw-r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2017-09-27 11:28:10.492205575 +0000
Modify: 2017-07-18 14:01:52.000000000 +0000
Change: 2017-09-27 11:25:30.646861372 +0000
 Birth: -```

**Comment by jlumme** [comment]
Removing docker image and clearing the cache fixed this issue for me, sorry for the inconvenience :)
